apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-app.fullname" . }}-config
  labels:
    {{- include "nginx-app.labels" . | nindent 4 }}
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections 1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        sendfile        on;
        keepalive_timeout  65;

        server {
            listen       {{ .Values.service.targetPort }};
            server_name  _;

            {{- if .Values.auth.enabled }}
            auth_basic           "Restricted";
            auth_basic_user_file /etc/nginx/.htpasswd;
            {{- end }}

            root   {{ .Values.nginx.rootPath }};
            index  {{ .Values.nginx.indexFile }};

            location / {
                try_files $uri $uri/ =404;
            }

            location = {{ .Values.nginx.healthPath }} {
                {{- if .Values.auth.enabled }}
                auth_basic off;
                {{- end }}
                access_log off;
                return 200 "OK";
            }
        }
    }
